### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by MrMonk3y** [zumbov2/deeplr#1]
Got this error:

Fehler in response_check(response) : 
  Please supply a valid auth_key parameter. (HTTP error 403)

They closed www.deepl.com/jsonrpc, didn't they?

**Comment by zumbov2** [comment]
They did...and moved it to www2.deepl.com/jsonrpc. Did you install the new version (1.1.0) from GitHub? Should be fixed.

**Comment by MrMonk3y** [comment]
Ou okay. Thank you for the quick response. No, I've installed it with pip.

**Comment by zumbov2** [comment]
Have you tried the new version yet?

**Comment by MrMonk3y** [comment]
Nope switched to a python wrapper. But www2.... did the trick. Guess yours will work too :)

**Comment by jamariani** [comment]
Hi David,
I'm new with deeplr (although I've used the website).
I've got 
Error in response_check(response) : 
  Please wait and send your request once again. (HTTP error 429)
in using any function of deeplr.
Could you help me please?
Thank you in advance

**Comment by jamariani** [comment]
Hi David,
I'm new with deeplr (although I've used the website).
I've got 
Error in response_check(response) : 
  Please wait and send your request once again. (HTTP error 429)
in using any function of deeplr.
Could you help me please?
Thank you in advance
