### ISSUE TITLE
Auth Paramater not valid

### ISSUE THREAD

**Issue by smroloes** [zumbov2/deeplr#8]
My old code started to produce the error yesterday, before that everything works as expected
`Error in response_check(response) : 
  Authorization failed. Please supply a valid auth_key parameter.`
  
  The `auth_key` is for sure valid, tried 3 different keys, all of them worked in python.

Full example
`available_languages2(auth_key = key)`

`Error in response_check(response) : 
  Authorization failed. Please supply a valid auth_key parameter.`

# EDIT:
I guess i found it, but thats in all of your functions. The key must be shifted to the header with the prefix "DeepL-Auth-Key"

for example your code
```
response <- httr::POST(url = "https://api-free.deepl.com/v2/languages", 
                         body = list(auth_key = key)) 
```

should be modified to
```
response <- httr::POST(url = "https://api-free.deepl.com/v2/languages", 
                       add_headers("Authorization" = paste("DeepL-Auth-Key",key))
                        )
```

**Comment by zumbov2** [comment]
Hi @smroloes, thank you very much for pointing this out. Hmm...all functions work for me without any problems. I will have a closer look at it soon. On which system and with which licence are you currently working?

**Comment by lisagarbe** [comment]
I have the same problem when using the package. I don't really know how to apply @smroloes solution. Do you have any advice on how to address this?

**Comment by zumbov2** [comment]
Hi @lisagarbe, thank you very much for your feedback. Could you please tell me on which system and with which licence you are currently working?

**Comment by lisagarbe** [comment]
Thanks for the quick reply. I am working on a Windows machine (Windows 10) using a DeepL Pro Advanced license.

**Comment by zumbov2** [comment]
The problem could be related to the Pro Advanced licence. I have customised all functions as suggested by @smroloes and uploaded a new version of the package to github (2.0.1).

Could you please give me feedback if this solves your problems.

``` r
install.packages("devtools")
devtools::install_github("zumbov2/deeplr")
```

**Comment by smroloes** [comment]
Hi i wrote my own translate function, maybe it helps you, maybe you have to install RcppSimdJson packge if you don't have already. Not elegant but it works.

``` r 
translate = function(text, source_lang = "DE" ,target_lang = "EN" ,key ){
  require(RcppSimdJson)
  namen= names(text)
  headers = c(
    'Authorization' = paste('DeepL-Auth-Key', key),
    'Content-Type' = 'application/json'
  )
  if(length(text)==1) text = list(text)
  h =   httr::POST(url="https://api-free.deepl.com/v2/translate",
                   add_headers(headers),
                   body=list("text"= text, target_lang=target_lang), encode = "json"
  )
  erg = RcppSimdJson::fparse(h$content)$translations$text
  names(erg) = namen
  return(erg)
}
```

Edit: Try to fix the linebreaks here, but failed... So not a code block...

**Comment by zumbov2** [comment]
Hi @smroloes, thanks for your fix. Could you try the latest version (2.0.1) and give me some feedback.

```r
install.packages("devtools")
devtools::install_github("zumbov2/deeplr")
```

**Comment by lisagarbe** [comment]
thanks for your support, Unfortunately, I am still getting the same error message when using the deeplr package:

Error in `purrr::pmap_chr()`:
ℹ In index: 1.
Caused by error in `response_check()`:
! Authorization failed. Please supply a valid auth_key parameter.

And when using the code @smroloes shared, I am getting the following error message regardless of what input data (list or character vector) I use: 

Fehler in RcppSimdJson::fparse(h$content) : 
  'json=' must be a non-empty character vector, raw vector, or a list containing raw vectors

Will try to figure out the problem and let you know once it's solved!

**Comment by zumbov2** [comment]
Thanks for your feedback! Have you change the url in @smroloes code to _https://api.deepl.com/v2/translate_ ?

In the [documentation](https://www.deepl.com/de/pro/change-plan#team) I see that your license type allows single sign-on. Are you using this feature?

**Comment by lisagarbe** [comment]
Unfortunately, I couldn't figure out the problem. Both, your and @smroloes functions work just fine with the free DeepL but not with the Pro/Advanced version.

**Comment by zumbov2** [comment]
hey @lisagarbe, sorry for not seeing the obvious. To use `deeplr`, you need a [developer account](https://www.deepl.com/de/pro#developer) (DeepL API Free, API Pro or API Business).

In the [API documentation](https://www.deepl.com/de/docs-api/api-access/general-information) you'll see that "[i]f you intend to integrate DeepL Pro into a CAT tool or another tool assisting translation, please contact [cat-tool.support@DeepL.com](mailto:cat-tool.support@DeepL.com)."
