### ISSUE TITLE
DeepL API key not accepted

### ISSUE THREAD

**Issue by dhub100** [zumbov2/deeplr#9]
I have a valid deepl API key (XXXXXX) which I verified with this link:
https://api.deepl.com/v2/translate?auth_key=XXXXXX&text=Hello&target_lang=de 

**My R syntax**
library(deeplr)
available_languages2(auth_key = ("XXXXXX")

**I get the following answer**
Fehler in response_check(response) : 
  Authorization failed. Please supply a valid auth_key parameter.

Can you please advise? Thank you.

**Comment by zumbov2** [comment]
Hi @dhub100 

Thanks for your feedback. I just gave it a try with my own developer key and it worked. Do you have a [developer key](https://www.deepl.com/en/pro/change-plan#developer)? `deeplr` only works with developer keys...

There is a free version (DeepL API Free) and a paid version (DeepL API Pro). With the former you use functions that end with a 2 (e.g. `available_languages2`), with the latter you use functions that end without a 2 (e.g. `available_languages`).

**Comment by dhub100** [comment]
Hi David

Sorry, I was not aware of the "2" that makes the difference between Free
and Pro. Last Monday I upgraded to Pro and this obviously caused the error.

My R script runs as expected now. Thanks a lot for your swift response!

Best,
Daniel


Am Do., 28. März 2024 um 13:28 Uhr schrieb David Zumbach <
***@***.***>:
